export class Emoji {
	constructor(public code: string) {}
}
export const emojis = [
	new Emoji('😅'),
	new Emoji('🙄'),
	new Emoji('😂'),
	new Emoji('👌'),
	new Emoji('❤'),
	new Emoji('😍'),
	new Emoji('🤣'),
	new Emoji('😊'),
	new Emoji('🙏'),
	new Emoji('💕'),
	new Emoji('😭'),
	new Emoji('🔥'),
	new Emoji('😘'),
	new Emoji('👍'),
	new Emoji('🥰'),
	new Emoji('😎'),
	new Emoji('😆'),
	new Emoji('😁'),
	new Emoji('😉'),
	new Emoji('🤔'),
	new Emoji('😔'),
	new Emoji('😜'),
	new Emoji('😒'),
	new Emoji('😩'),
	new Emoji('😁'),
	new Emoji('👏'),
	new Emoji('💔'),
	new Emoji('💖'),
	new Emoji('💙'),
	new Emoji('😢'),
	new Emoji('💪'),
	new Emoji('💜'),
	new Emoji('🤗'),
	new Emoji('😇'),
	new Emoji('🌹'),
	new Emoji('🤦'),
	new Emoji('🎉'),
	new Emoji('💞'),
	new Emoji('✌'),
	new Emoji('✨'),
	new Emoji('🤷'),
	new Emoji('😱'),
	new Emoji('😌'),
	new Emoji('🌸'),
	new Emoji('🙌'),
	new Emoji('😋')
];
